version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: project_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
