version: 2
jobs:
  build:
    # Primary container image where all commands run
    
    docker:
      - image: circleci/node:10
        environment:
          ENV_PATH: ./.env.testing
    
    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_DB: project_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        
    steps:
      - checkout
